version: '3.8'

services:
  backend:
    build: .
    container_name: surya_backend
    restart: always
    ports:
      - "15026:15026"
    environment:
      - PORT=15026
      - JWT_SECRET=supersecretkey123
      - APP_BASE_URL=https://ykd.dev:15026
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads